dist: xenial
language: ruby
cache: bundler

rvm:
  - ruby-head
  - 2.6.5
  - 2.5.7
  - 2.4.9
  - 2.3.8

before_install:
  - gem update --system
  - gem install bundler -v "~> 2.0"

install:
  - bundle install --jobs=3 --retry=3
  - bundle exec appraisal install --jobs=3 --retry=3

script:
  - bundle exec rubocop
  - bundle exec appraisal rake

matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true

services:
  - redis
  - memcached
